### ISSUE TITLE
[Feature Request] Core for Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/blueMSX-libretro#121]
Hi there, just wondering why this core is not available on Retroarch for Wii. Any chance it could be made to work on the Wii? Thanks.

**Comment by metallic77** [comment]
i compiled it on devkitpro and already proposed to include to Wii nightlies too.

here is proof
https://www.dropbox.com/s/9ji8lqh8ujgf4nx/msx_handy.zip?dl=0

**Comment by Edu789** [comment]
Thanks, I will test ...

**Comment by metallic77** [comment]
There is already a new core on nightlies.

**Comment by Edu789** [comment]
I tested both here, bluemsx just isn't taking Spectravideo games, and fmsx isn't taking MSX2 + and MSX turbo R. games.
Both do not work as Wifflow Lite* plugins.
*Wiiflow is a homebrew USB loader for the Nintendo Wii video game console.  It displays your games and apps in full 3D box coverflow display and is capable of launching Wii and WiiWare/VC games, homebrew titles, and GameCube games. Plus with WiiFlows intuitive plugin system you can launch and play several classic retro games via their respective homebrew emulator.
