### ISSUE TITLE
.dsk support?

### ISSUE THREAD

**Issue by duiz** [libretro/blueMSX-libretro#22]
The original BlueMSX has support for .dsk format, as well as a hotkey to switch between dsks within a zip archive. Sadly the libretro doesn't seem to support dsk games, leaving much for MSX2 and beyond library left out.

Is there any plans or possibility to add dsk support?

**Comment by meepingsnesroms** [comment]
Duplicate #13 
I am currently working on fixing this.

**Comment by orbea** [comment]
@meepingsnesroms Awesome, it would be greatly appreciated!

**Comment by meepingsnesroms** [comment]
It's already done now!

**Comment by duiz** [comment]
Will BlueMSX-libretro include the swap disk feature that's in standalone BlueMSX? (All disk in 1 zip, alt+F9 to swap between them)

**Comment by meepingsnesroms** [comment]
Maybe later,right now it only supports loading disks the same way you load roms through the file manager.
