### ISSUE TITLE
MSX2 support (and not MSX2+)

### ISSUE THREAD

**Issue by Sebbeug** [libretro/blueMSX-libretro#26]
Acutally, we can only switch between MSX and MSX2+ type.
It would be nice to have MSX2 too (MSX2 european).

WHY ? 

Because of japan translation in all MULTI language games which are automatically switched to japan in MSX2+ mode.

For exemple, try to play Kings Valley 2 MSX2 version, you'll have title in JAPAN.
Other exemple, in Nemesis2, you'll have intro's texts in japan ! 
(cause of MSX2+ bios which is only japan)

**Comment by gingerbeardman** [comment]
As of today you can switch between MSX2+, MSX2, MSXTurboR, MSX1

**Comment by Sebbeug** [comment]
TurboR too ?
Thx.
