### ISSUE TITLE
Can't run Coleco roms

### ISSUE THREAD

**Issue by ojaksch** [libretro/blueMSX-libretro#27]
According to the wiki this core should play Coleco .col roms but mine doesn't. When running the core displays the MSX logo, changes to "MSX BASIC" ... "OK" and stops. No further input possible nor anything at stdout.
MSX/MSX2/SG1000 are working fine.

**Comment by Oggom** [comment]
Duplicate of https://github.com/libretro/blueMSX-libretro/issues/8

**Comment by bigboo3000** [comment]
Recalbox added this in their code:
https://github.com/recalbox/recalbox-buildroot/blob/28813082a8b445c468d4a5fab2f2c1cf3ad2fd2b/package/libretro-bluemsx/bluemsx-001-colecovision.patch

**Comment by ojaksch** [comment]
Thanks for this hint. Can confirm that patch applies cleanly and, most important, WORKS.

**Comment by twinaphex** [comment]
Can't apply it cleanly here at all.

**Comment by ojaksch** [comment]
I beg your pardon. Are you sure?
In my last post I did this with 109 and restested with 110 yet but patch still applys cleanly and core works fine (Arch x86-64)

makepkg
==> Making package: libretro-bluemsx-git 110.6d9d3f7-1 (Fri Aug 19 17:06:03 CEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning blueMSX-libretro git repo...
Cloning into bare repository '/tmp/yaourt-tmp-larry/aur-libretro-bluemsx-git/blueMSX-libretro'...
remote: Counting objects: 2526, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2526 (delta 0), reused 0 (delta 0), pack-reused 2523
Receiving objects: 100% (2526/2526), 3.83 MiB | 1.04 MiB/s, done.
Resolving deltas: 100% (1472/1472), done.
Checking connectivity... done.
  -> Found bluemsx_libretro.info
  -> Found bluemsx-001-colecovision.patch
==> Validating source files with md5sums...
    blueMSX-libretro ... Skipped
    bluemsx_libretro.info ... Skipped
    bluemsx-001-colecovision.patch ... Skipped
==> Extracting sources...
  -> Creating working copy of blueMSX-libretro git repo...
Cloning into 'blueMSX-libretro'...
done.
==> Starting pkgver()...
==> Starting build()...
patching file Src/Input/ColecoJoystick.c
patching file Src/Input/InputEvent.c
patching file Src/Input/InputEvent.h
patching file Src/Input/MsxJoystick.c
patching file libretro.c
cc -c -o libretro.o libretro.c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -O3 -DLOG_PERFORMANCE -fPIC -D__LIBRETRO__  -DSINGLE_THREADED -DVIDEO_COLOR_TYPE_RGB565 -DZ80_CUSTOM_CONFIGURATION -DNO_FRAMEBUFFER -w  -I. -I./libretro-common/include -I./Src/Arch -I./Src/Bios -I./Src/Board -I./Src/BuildInfo -I./Src/Common -I./Src/Debugger -I./Src/Emulator -I./Src/IoDevice -I./Src/Language -I./Src/Media -I./Src/Memory -I./Src/Resources -I./Src/SoundChips -I./Src/TinyXML -I./Src/Unzip -I./Src/Utils -I./Src/VideoChips -I./Src/VideoRender -I./Src/Z80 -I./Src/Input -I./Src/Libretro
[...]
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "libretro-bluemsx-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: libretro-bluemsx-git 110.6d9d3f7-1 (Fri Aug 19 17:06:13 CEST 2016)

**Comment by twinaphex** [comment]
send a pull request then.

**Comment by rockaddicted** [comment]
@bigboo3000 @ojaksch If this patch has not be pushed upstream, it is because it is a dirty hack for tests. If you want to add it upstream, that need to be reworked before.

**Comment by ojaksch** [comment]
**@rockaddicted** I agree. Would only mention that patch is working for _me_. Hope that somebody will review this and send it to upstream.

**Comment by saftle** [comment]
Is this still in the works? Or is using Mame/Mess2014 a more viable option at the moment?

**Comment by SedrynTyros** [comment]
It would be great to have this functionality.  Is this still a work-in-progress?

**Comment by Tatsuya79** [comment]
It should work now.
https://github.com/libretro/blueMSX-libretro/pull/41#event-1148586688

**Comment by ojaksch** [comment]
Great, it IS working. For those puzzling around how to get this running: Change bluemsx_msxtype to ColecoVision .

**Comment by bigboo3000** [comment]
Yeah it's working great!
just don't forget to add the BIOS here:
\system\Machines\COL - ColecoVision\coleco.rom

**Comment by Tatsuya79** [comment]
You can probably close this issue now.
There's support for Sega and Spectravideo too.

**Comment by ojaksch** [comment]
Right, thanks for waking me up :)
