### ISSUE TITLE
Controllers option is missing from RGUI on RPI3

### ISSUE THREAD

**Issue by msheehan79** [libretro/blueMSX-libretro#50]
When the core first launches the Controllers option is not present in Quick Options of RGUI. If I go to Settings/Input/Input User 1 Binds and change the controller type there, after that the Controllers option reappears in the Quick Options menu and input works normally again.

This is on a RPI3 running RetroPie, RetroArch 1.6.7 updated from source today.

**Comment by fr500** [comment]
Are you sure your retroarch is up to date?
It certainly doesn't seem like it. The controllers stuff I changed on the weekend (force them to show even if  no descriptors are available)

**Comment by msheehan79** [comment]
Hi and thanks for responding. I saw some commits related to the keyboard so I had updated RetroArch from source within RetroPie's setup script earlier tonight before posting this - it shows v1.6.7 as the major version, but not sure where to check the exact build if you can point me in the right direction on where that info would be. 

I wonder if the updating from source via the RetroPie-Setup script is not pulling the absolute latest commits - that would explain a lot.

**Comment by fr500** [comment]
no idea about retropie but you can get the commit in information/system information
look for Git version

**Comment by msheehan79** [comment]
thank you. That was it, build 8e8bdaa from about 26 days ago. Apparently updating from source within RetroPie does not mean it is pulling the latest build, I will remember that for next time.

I'm sure all will be good once I update. And also - thank you for implementing this! I've just started setting up MSX/X68000 recently and being able to map keys from within RA is going to be a huge help since so many games have different key commands.
