### ISSUE TITLE
Feature Request - Generic Keyboard Mapper

### ISSUE THREAD

**Issue by KMFDManic** [libretro/blueMSX-libretro#69]
I run this amazing Core on NESC/SNESC!  I previously had this same feature request for the great Commodore 64 (Vice Core), as stated here...

https://github.com/libretro/vice-libretro/issues/7

The end result of that request was perfect for NESC/SNESC   Here is it, in action...Go about 2 minutes in!

https://www.youtube.com/watch?v=dBn9MkHUA_E&feature=youtu.be

Thank you so much for your time and consideration in this Feature Request!  

I love both FMSX & BlueMSX Cores, and am hoping to get this added to both:)

**Comment by fr500** [comment]
That's not using the generic keymapper, bluemsx has it already and that's the actual generic keymapper unlike the one you showed here.

![image](https://user-images.githubusercontent.com/1721040/33740195-d3b94c8a-db6d-11e7-91e9-fb7632ff6d36.png)

![image](https://user-images.githubusercontent.com/1721040/33740201-d7fd04b2-db6d-11e7-9c1a-56f8376ffb8f.png)
