### ISSUE TITLE
Repository is missing BIOS files.

### ISSUE THREAD

**Issue by Hedonium** [libretro/blueMSX-libretro#77]
![](https://forums.libretro.com/uploads/default/original/2X/5/538c34c906611a0b0c7acf58733c05f2c9e0f223.png)

The Databases and Machines directories in this repository are missing BIOS files from a full installation of blueMSX.

Why? Does the repository need updating?

**Comment by gcharlie84** [comment]
Bios are proprietary and copyrighted code, so legally they can be packed in with emulators without permission from the original developer. So you'll have to find them elsewhere, or dump the code yourself from the actual machines bios chips.

**Comment by Hedonium** [comment]
The BIOS files I'm talking about are freely disturbed with blueMSX. The real problem here is whether this repository's BIOS files are in sync with standalone blueMSX's BIOS files or not.

**Comment by paradadf** [comment]
Hello! I'd like to add the missing files in the Machines directory, as they are shipped with the blueMSX emulator and actually belong to the c-bios association, which allows to freely ship them. Check this out: http://cbios.sourceforge.net/

Can someone please give me the "go" for the PR?

**Comment by clach04** [comment]
@paradadf I'm still getting used to the libretro system so this my idea may be off-base. I think there are two LR ports for MSX; fMSX and blueMSX. It may make sense to put C-BIOS into a different package that both emulators then rely on.

It will be quicker to attach to this repo though :)
