### ISSUE TITLE
(libretro) ColecoVision/Spectravideo/SG-1000 support

### ISSUE THREAD

**Issue by Oggom** [libretro/blueMSX-libretro#8]
The libretro port of blueMSX always assumes it's booting up a MSX game which makes it currently impossible to play ~~ColecoVision~~, Spectravideo and SG-1000 games with this core.

Edit:  ColecoVision is now supported https://github.com/libretro/blueMSX-libretro/pull/41

**Comment by HerbFargus** [comment]
I can also confirm this issue- there are three core options msx, msx2+, and MSXturboR, there should be 3 more core options for ColecoVision, Spectravideo, and SG-1000 games

**Comment by obert01** [comment]
Hello,

For your information, that branch of bluemsx-libretro can be configured to run Colecovision games:
https://github.com/HerbFargus/blueMSX-libretro

You have to place the "coleco.rom" BIOS file in the folder "Machines/COL - ColecoVision" folder. 

You also have to edit your retroarch-core-options.cfg as follows:
```
bluemsx_msxtype = "COL - ColecoVision"
```

You can boot up a game, butyou are immediately limited because the specific numeric keys of the ColecoVision pad are not mapped for the moment.

**Comment by HerbFargus** [comment]
Yes I was aware of that. (If yoy look through my branch you'll see i added it as a core option in the code) I was trying to figure out how to get the joypad stuff integrated so my games would actually work but I lack the coding skills at the moment unfortunately. Might have to wait until twinaphex adds the option in the master here. Colecovision would be a fantastic addition.

**Comment by Redemp** [comment]
Any more news on this? @twinaphex

**Comment by Mad-Mega** [comment]
How would i be able to het a .SO file of BlueMSX ?

**Comment by Zombie-Ryushu** [comment]
Can someone assist in clarifying how to configure RetroArch for Colecovision support with blueMSX?

**Comment by hizzlekizzle** [comment]
@Zombie-Ryushu That sort of question belongs on the forums. https://forums.libretro.com

Github issues are for development issues, not end-user support.

**Comment by Tatsuya79** [comment]
Forgot to post it here too: I added the support and gamepad mapping for Coleco.

https://github.com/libretro/blueMSX-libretro/pull/41

Please read the info file for keys explanation.

**Comment by Oggom** [comment]
@Tatsuya79 Neat. Thank you very much! :octocat:

**Comment by Tatsuya79** [comment]
The basics should be covered.
https://github.com/libretro/blueMSX-libretro/pull/43

**Comment by Oggom** [comment]
Much appreciated, thanks again 👍

**Comment by HerbFargus** [comment]
Confirming this works (at least for colecovision, haven't tested the others yet)

thanks for your work on this @Tatsuya79 I've been waiting for this for a long time.
